
USE PTBPABD;

-- Questão 1
CREATE USER User_A WITH PASSWORD = 'senhaA123';
CREATE USER User_B WITH PASSWORD = 'senhaB123';
CREATE USER User_C WITH PASSWORD = 'senhaC123';
CREATE USER User_D WITH PASSWORD = 'senhaD123';
CREATE USER User_E WITH PASSWORD = 'senhaE123';

-- Questão 2
GRANT SELECT, INSERT, UPDATE, DELETE ON STUDENT TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON INSTRUCTOR TO User_A WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON COURSE TO User_A WITH GRANT OPTION;

-- Questão 3
